django/atg/urls.py
from django.contrib import admin
from django.urls import path, include
from atg_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('atg_app.urls')),
    path('logout/',views.user_logout,name='user_logout'), 
]

django/atg_app/urls.py
from django.urls import path
from . import views
app_name='atg_app'
urlpatterns = [
    path('',views.index,name='index'),
    path('home/',views.home,name='home'),
    path('home/<str:state>/',views.category_data,name='category_data'),
    path('home/<str:state>/<int:cat>/',views.subcategory_data,name='subcategory_data'),
    path('home/<str:state>/<int:cat>/<int:subcat>',views.jobs_data,name='jobs_data'),
    path('home/<str:state>/<int:cat>/<int:subcat>/<int:job>',views.job_details,name='job_details'),
]

django/atg_app/models.py
from dataclasses import Field
from django.db import models

# Create your models here.
class JobType1(models.Model):
    id= models.AutoField(primary_key=True)
    Category = models.CharField(max_length=256,unique=True)

class JobType2(models.Model):
    id= models.AutoField(primary_key=True)
    Category = models.ForeignKey(JobType1,to_field='Category',db_column='Category',on_delete=models.CASCADE  )
    Subcategory=models.CharField(max_length=256,unique=True)

class States(models.Model):
    id= models.AutoField(primary_key=True)
    State =models.CharField(max_length=256,unique=True)

class CompanyDetails(models.Model):
    id= models.AutoField(primary_key=True)
    Name =models.CharField(max_length=256)
    Field =models.CharField(max_length=256)
    Headquarters =models.CharField(max_length=256)
    Description=models.CharField(max_length=2000)
    class Meta:
        unique_together = ['Name', 'Field']

class Jobs(models.Model):
    id= models.AutoField(primary_key=True)
    Company_id= models.ForeignKey(CompanyDetails,db_column="Company_id",on_delete=models.CASCADE)
    JobPosition =models.CharField(max_length=256)
    Location =models.CharField(max_length=256)
    WorkType=models.CharField(max_length=2000)
    State=models.ForeignKey(States,to_field='State',db_column='State',on_delete=models.CASCADE)
    Subcategory=models.ForeignKey(JobType2,to_field='Subcategory',db_column="Subcategory",on_delete=models.CASCADE)
    class Meta:
        unique_together = ['Company_id', 'JobPosition']

django/atg_app/forms.py
from django import forms
from django.contrib.auth.models import User

class SignupForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','email','password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'input','placeholder':'Enter Username','id':'username'}),
            'email':    forms.EmailInput(attrs={'class':'input','placeholder':'Enter Email','id':'email'}),
            'password': forms.PasswordInput(attrs={'class':'input','placeholder':'Enter Password','id':'password'})
        }

class LoginForm(forms.ModelForm):
    class Meta:
        model=User
        fields=['username','password']
        widgets = {
            'username': forms.TextInput(attrs={'class':'input','placeholder':'Enter Username','id':'log_username'}),
            'password': forms.PasswordInput(attrs={'class':'input','placeholder':'Enter Password','id':'log_password'})
        }

django/atg_app/views.py
from django.urls import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect
from . import forms
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import login, logout,authenticate
from . import models
from django.contrib.auth.models import User

#login and sigin page view
def index(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("atg_app:home"))
    if request.method=="POST":
        if len(request.POST)==3:
            username=request.POST['username']
            password=request.POST['password']
            user=authenticate(username=username,password=password)
            if user:
                if user.is_active:
                    login(request,user)
                    return HttpResponseRedirect(reverse('atg_app:home'))
                else:
                    messages.add_message(request,messages.ERROR,"account is not active")
                    return HttpResponseRedirect(reverse('atg_app:index'))
            else:
                messages.add_message(request,messages.ERROR,"invalid details")
                return HttpResponseRedirect(reverse('atg_app:index'))
        else:
            username=request.POST['username']
            email=request.POST['email']
            password=request.POST['password']
            if(len(User.objects.filter(username=username))!=0): 
                messages.add_message(request,messages.ERROR,"choose another username")
                return HttpResponseRedirect(reverse('atg_app:index'))
            elif(len(User.objects.filter(email=email))!=0):
                messages.add_message(request,messages.ERROR,"choose another email")
                return HttpResponseRedirect(reverse('atg_app:index'))
            else:
                user=User.objects.create_user(username=username,email=email,password=password)
                user.save()
                login(request,user)
                return HttpResponseRedirect(reverse('atg_app:home'))
    return render(request,"index.html",context={'signin_form':forms.SignupForm(),'login_form':forms.LoginForm()}) 

#state page view
@login_required
def home(request):
    states=models.States.objects.all()
    return render(request,'home.html',context={'states':states,'current_user':request.user.username})

#category page view
@login_required
def category_data(request,**kwargs):
    categories=models.JobType1.objects.all()
    return render(request,'categories.html',context={'categories':categories,'state':kwargs['state'],'current_user':request.user.username})

#subcategory page view
@login_required
def subcategory_data(request,**kwargs):
    subcategories=models.JobType2.objects.filter(Category=models.JobType1.objects.get(id=kwargs['cat']).Category)
    return render(request,'subcategories.html',context={'subcategories':subcategories,'state':kwargs['state'],'cat':kwargs['cat'],'current_user':request.user.username})

#jobs page view
@login_required
def jobs_data(request,**kwargs):
    companies=models.CompanyDetails.objects.all()
    jobs=models.Jobs.objects.filter(State=kwargs['state']).filter(Subcategory=models.JobType2.objects.get(id=kwargs['subcat']).Subcategory)
    return render(request,'jobs.html',context={'jobs':jobs,'current_user':request.user.username,'companies':companies,'state':kwargs['state'],'cat':kwargs['cat'],'subcat':kwargs['subcat']})

#a particular job page view
@login_required
def job_details(request,**kwargs):
    job=models.Jobs.objects.get(id=kwargs['job'])
    return render(request,'job_details.html',context={'job':job,'current_user':request.user.username})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('atg_app:index'))

django/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jobs Scraper</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <style>
      .container{
        position: absolute;
        text-align: center;
        width: 80vw;
        height: 75vh;
        margin: auto;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
      }
    </style>
</head>

<body class="body" >
    <section id="navbarsection" > 
      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top flex-column " >
        <div class="container-fluid">
          <a class="navbar-brand mb-0 h1 mx-auto " href="/">Jobs Scraper</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" id="Searching" placeholder="Search" aria-label="Search">
              </form>
              <div class="dropdown">
                <button class="btn  dropdown-toggle dropdown-button" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  {{current_user}}
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item" href="{% url 'user_logout' %}">logout</a>
                </div>
              </div>
            </ul>
          </div>
        </div>
      </nav> 
    </section>
    {% block body %} {% endblock body %} 
</body>
</html> 

django/templates/categories.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
  {% if categories|length == 0 %}  
    <div class="alert alert-dark" role="alert">
      No record found
    </div>
  {% else %} 
    <div id="table-wrapper">
      <div id="table-scroll">
        <table class="table table_database table-striped table-bordered"  id="table_database">
          <thead>
            <tr>
              <th scope="col">Serial no</th>
              <th scope="col">Category</th>
            </tr>
          </thead>
          <tbody id="myTable">
          {% for item in categories %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td id="category"><a href="{% url 'atg_app:subcategory_data' state item.id %}">{{item.Category}}</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}
</div>
{% endblock body %}

django/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
  {% if states|length == 0 %}  
    <div class="alert alert-dark" role="alert">
      No record found
    </div>
  {% else %} 
    <div id="table-wrapper">
      <div id="table-scroll">
        <table class="table table_database table-striped table-bordered"  id="table_database">
          <thead>
            <tr>
              <th scope="col">Serial no</th>
              <th scope="col">State</th>
            </tr>
          </thead>
          <tbody id="myTable">
          {% for item in states %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td id="state"><a href="{% url 'atg_app:category_data' item.State %}">{{item.State}}</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}
</div>
{% endblock body %}

django/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Jobs Scraper</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <style>
      .container{
        position: absolute;
        text-align: center;
        width: 80vw;
        height: 75vh;
        margin: auto;
        top: 50%;
        left: 50%;
        transform: translate(-50%,-50%);
      }
    </style>
</head>

<body class="body" >
    <section id="navbarsection" > 
      <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top flex-column " >
        <div class="container-fluid">
          <a class="navbar-brand mb-0 h1 mx-auto " href="/">Jobs Scraper</a>
        </div>
      </nav> 
    </section>
    <div class="container" style="position: absolute;width: 60vw;height: 80vh;margin: auto;top: 50%;left: 50%;transform: translate(-50%,-50%);">
      <div id="flash_container">
        {% if messages %}
          {% for message in messages %}
          <div class="alert alert-warning alert-dismissible fade show my-0" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          {% endfor %}
          </div>
        {% endif %}
      </div>
      <div class="signup">Sign Up</div>
      <div class="login">Log In</div>
      
      <div class="signup-form">
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-group row">
              {{ signin_form.username}}
            <small id="username_check" class="form-text invalid-feedback" >
            </small>
          </div>
          <div class="form-group row">
              {{ signin_form.email }}
              <small id="emailcheck" class="form-text text-muted invalid-feedback">
              </small>
          </div>
          <div class="form-group row">
              {{signin_form.password }}
              <small id="passcheck" class="form-text invalid-feedback" >
              </small>
          </div>
          <button type="submit" id="signup_btn" class="btn btn-outline-primary btn-lg button" >Submit</button>
        </form>
      </div>
      
      <div class="login-form">
        <form action="" method="post">
          {% csrf_token %}
          <div class="form-group row">
            {{ login_form.username}}
            <small id="log_name_check" class="form-text invalid-feedback" >
            </small>
          </div>
          <div class="form-group row">
              {{ login_form.password }}
              <small id="log_passcheck" class="form-text invalid-feedback"  >
              </small>
          </div>
          <button type="submit" id="login_btn" class="btn btn-outline-primary btn-lg button" >Submit</button>
        </form>
      </div>
    </div>
</body>
</html>

django/templates/job_details.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <h2>{{job.JobPosition}}</h2>
    <br>
    <h6>{{job.Company_id.Name}}</h6>
    <br>
    <p>{{job.Company_id.Description}}</p>
  </div>  
{% endblock body %}

django/templates/jobs.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    {% if jobs|length == 0 %}  
      <div class="alert alert-dark" role="alert">
        No record found
      </div>
    {% else %} 
      <div id="table-wrapper">
        <div id="table-scroll">
          <table class="table table_database table-striped table-bordered"  id="table_database">
            <thead>
              <tr>
                <th scope="col">Serial no</th>
                <th scope="col">JobPosition</th>
                <th scope="col">Company</th>
                <th scope="col">Field</th>
                <th scope="col">Action</th> 
              </tr>
            </thead>
            <tbody id="myTable">
            {% for item in jobs %}
              <tr>
                <th scope="row">{{forloop.counter}}</th>
                <td id="jobPosition">{{item.JobPosition}}</td>
                <td>{{item.Company_id.Name}}</td>
                <td>{{item.Company_id.Field}}</td>
                <td>
                    <a href="{% url 'atg_app:job_details' state cat subcat item.id %}"  type="button"  class="btn btn-outline-success btn-sm mr-1" >Read More..</a>
                </td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    {% endif %}
  </div>  
{% endblock body %}

django/templates/subcategories.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
  {% if subcategories|length == 0 %}  
    <div class="alert alert-dark" role="alert">
      No record found
    </div>
  {% else %} 
    <div id="table-wrapper">
      <div id="table-scroll">
        <table class="table table_database table-striped table-bordered"  id="table_database">
          <thead>
            <tr>
              <th scope="col">Serial no</th>
              <th scope="col">Subcategory</th>
            </tr>
          </thead>
          <tbody id="myTable">
          {% for item in subcategories %}
            <tr>
              <th scope="row">{{forloop.counter}}</th>
              <td id="subcategory"><a href="{% url 'atg_app:jobs_data' state cat item.id %}">{{item.Subcategory}}</a></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  {% endif %}
</div>

{% endblock body %}